"""lay remove

Revision ID: 39d14c4e414f
Revises: cef78c397094
Create Date: 2025-06-19 15:28:03.473273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39d14c4e414f'
down_revision = 'cef78c397094'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass

def downgrade():
    pass