"""migrate

Revision ID: 5486b6e69bf9
Revises: cf89de628ff8
Create Date: 2025-06-19 11:29:40.208289

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5486b6e69bf9'
down_revision = 'cf89de628ff8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('social_channel_subscribers')
    
def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('social_channel_subscribers',
    sa.Column('channel_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('subscribed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['social_channels.id'], name='social_channel_subscribers_channel_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='social_channel_subscribers_user_id_fkey'),
    sa.PrimaryKeyConstraint('channel_id', 'user_id', name='_channel_user_uc')
    )
    # ### end Alembic commands ###
