"""empty message

Revision ID: 6e081e6a493d
Revises: 773eade80ffc
Create Date: 2025-06-09 03:27:29.672776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e081e6a493d'
down_revision = '773eade80ffc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('library_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('check_in_time', sa.DateTime(), nullable=True),
    sa.Column('check_out_time', sa.DateTime(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_channel_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('security_type', sa.String(length=20), nullable=True),
    sa.Column('security_payload_hash', sa.String(length=255), nullable=True),
    sa.Column('_metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='_user_category_name_uc')
    )
    op.create_index('idx_user_channel_category_user_order', 'user_channel_category', ['user_id', 'order'], unique=False)
    op.create_index(op.f('ix_user_channel_category_user_id'), 'user_channel_category', ['user_id'], unique=False)
    op.create_table('user_saved_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('item_type', sa.String(length=50), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('saved_at', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('custom_tags', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'item_type', 'item_id', name='_user_saved_item_uc')
    )
    op.create_index('idx_user_item_type_id', 'user_saved_item', ['user_id', 'item_type', 'item_id'], unique=False)
    op.create_index(op.f('ix_user_saved_item_item_id'), 'user_saved_item', ['item_id'], unique=False)
    op.create_index(op.f('ix_user_saved_item_item_type'), 'user_saved_item', ['item_type'], unique=False)
    op.create_index(op.f('ix_user_saved_item_saved_at'), 'user_saved_item', ['saved_at'], unique=False)
    op.create_index(op.f('ix_user_saved_item_user_id'), 'user_saved_item', ['user_id'], unique=False)
    op.add_column('message', sa.Column('file_id', sa.Integer(), nullable=True))
    op.alter_column('message', 'content',
               existing_type=sa.TEXT(),
               nullable=True)
    op.create_foreign_key(None, 'message', 'social_files', ['file_id'], ['id'], ondelete='SET NULL')
    

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('message', 'content',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('message', 'file_id')
    op.drop_index(op.f('ix_user_saved_item_user_id'), table_name='user_saved_item')
    op.drop_index(op.f('ix_user_saved_item_saved_at'), table_name='user_saved_item')
    op.drop_index(op.f('ix_user_saved_item_item_type'), table_name='user_saved_item')
    op.drop_index(op.f('ix_user_saved_item_item_id'), table_name='user_saved_item')
    op.drop_index('idx_user_item_type_id', table_name='user_saved_item')
    op.drop_table('user_saved_item')
    op.drop_index(op.f('ix_user_channel_category_user_id'), table_name='user_channel_category')
    op.drop_index('idx_user_channel_category_user_order', table_name='user_channel_category')
    op.drop_table('user_channel_category')
    op.drop_table('library_log')
    # ### end Alembic commands ###
