"""empty message

Revision ID: 7711b70ae17b
Revises: 
Create Date: 2025-06-16 13:43:11.852789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7711b70ae17b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('lab',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('social_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('talent_club_community',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('is_leader', sa.Boolean(), nullable=False),
    sa.Column('force_password_change', sa.Boolean(), nullable=False),
    sa.Column('is_tc_leader', sa.Boolean(), nullable=False),
    sa.Column('is_tc_member', sa.Boolean(), nullable=False),
    sa.Column('leader_id', sa.Integer(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('sex', sa.String(length=20), nullable=True),
    sa.Column('profile_photo_url', sa.String(length=255), nullable=True),
    sa.Column('grade', sa.String(length=10), nullable=True),
    sa.Column('section', sa.String(length=10), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('lab_id', sa.Integer(), nullable=True),
    sa.Column('home_city', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['lab_id'], ['lab.id'], ),
    sa.ForeignKeyConstraint(['leader_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_full_name'), 'user', ['full_name'], unique=False)
    op.create_index(op.f('ix_user_grade'), 'user', ['grade'], unique=False)
    op.create_index(op.f('ix_user_leader_id'), 'user', ['leader_id'], unique=False)
    op.create_index(op.f('ix_user_section'), 'user', ['section'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('asset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('purchase_cost', sa.Float(), nullable=True),
    sa.Column('condition', sa.String(length=50), nullable=False),
    sa.Column('is_consumable', sa.Boolean(), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('last_maintenance_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('location_description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('added_by_user_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('lab_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['added_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['asset_category.id'], ),
    sa.ForeignKeyConstraint(['lab_id'], ['lab.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_added_by_user_id'), 'asset', ['added_by_user_id'], unique=False)
    op.create_index(op.f('ix_asset_category_id'), 'asset', ['category_id'], unique=False)
    op.create_index(op.f('ix_asset_lab_id'), 'asset', ['lab_id'], unique=False)
    op.create_index(op.f('ix_asset_name'), 'asset', ['name'], unique=False)
    op.create_index(op.f('ix_asset_status'), 'asset', ['status'], unique=False)
    op.create_table('behavior_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('recorded_by_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('behavior_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('is_resolved', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['recorded_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_behavior_student_date', 'behavior_record', ['student_id', 'date'], unique=False)
    op.create_index(op.f('ix_behavior_record_date'), 'behavior_record', ['date'], unique=False)
    op.create_index(op.f('ix_behavior_record_is_resolved'), 'behavior_record', ['is_resolved'], unique=False)
    op.create_index(op.f('ix_behavior_record_recorded_by_id'), 'behavior_record', ['recorded_by_id'], unique=False)
    op.create_index(op.f('ix_behavior_record_student_id'), 'behavior_record', ['student_id'], unique=False)
    op.create_table('library_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('check_in_time', sa.DateTime(), nullable=True),
    sa.Column('check_out_time', sa.DateTime(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mark',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=100), nullable=False),
    sa.Column('semester_1', sa.Float(), nullable=True),
    sa.Column('semester_2', sa.Float(), nullable=True),
    sa.Column('total', sa.Float(), nullable=True),
    sa.Column('average', sa.Float(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'subject', name='_student_subject_uc')
    )
    op.create_index('idx_mark_subject_average', 'mark', ['subject', 'average'], unique=False)
    op.create_index(op.f('ix_mark_average'), 'mark', ['average'], unique=False)
    op.create_index(op.f('ix_mark_student_id'), 'mark', ['student_id'], unique=False)
    op.create_index(op.f('ix_mark_subject'), 'mark', ['subject'], unique=False)
    op.create_table('notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('receiver_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('link_url', sa.String(length=255), nullable=True),
    sa.Column('notification_type', sa.String(length=50), nullable=True),
    sa.Column('related_object_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['receiver_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_notification_receiver_read', 'notification', ['receiver_id', 'is_read'], unique=False)
    op.create_index(op.f('ix_notification_is_read'), 'notification', ['is_read'], unique=False)
    op.create_index(op.f('ix_notification_receiver_id'), 'notification', ['receiver_id'], unique=False)
    op.create_index(op.f('ix_notification_related_object_id'), 'notification', ['related_object_id'], unique=False)
    op.create_index(op.f('ix_notification_sender_id'), 'notification', ['sender_id'], unique=False)
    op.create_index(op.f('ix_notification_timestamp'), 'notification', ['timestamp'], unique=False)
    op.create_table('parent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('preferred_contact_method', sa.String(length=20), nullable=True),
    sa.Column('receive_grade_updates', sa.Boolean(), nullable=True),
    sa.Column('receive_behavior_updates', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('request_type', sa.String(length=50), nullable=False),
    sa.Column('urgency', sa.String(length=20), nullable=False),
    sa.Column('requester_id', sa.Integer(), nullable=False),
    sa.Column('current_handler_id', sa.Integer(), nullable=True),
    sa.Column('last_forwarded_by_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('tier', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(), nullable=False),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('denial_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['current_handler_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['last_forwarded_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['requester_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_request_requester_status', 'request', ['requester_id', 'status'], unique=False)
    op.create_index('idx_request_status_tier', 'request', ['status', 'tier'], unique=False)
    op.create_index(op.f('ix_request_current_handler_id'), 'request', ['current_handler_id'], unique=False)
    op.create_index(op.f('ix_request_last_forwarded_by_id'), 'request', ['last_forwarded_by_id'], unique=False)
    op.create_index(op.f('ix_request_requester_id'), 'request', ['requester_id'], unique=False)
    op.create_index(op.f('ix_request_status'), 'request', ['status'], unique=False)
    op.create_index(op.f('ix_request_tier'), 'request', ['tier'], unique=False)
    op.create_index(op.f('ix_request_title'), 'request', ['title'], unique=False)
    op.create_table('secret_code',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('grade', sa.String(length=10), nullable=True),
    sa.Column('section', sa.String(length=10), nullable=True),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_secret_code_code'), 'secret_code', ['code'], unique=True)
    op.create_index(op.f('ix_secret_code_user_id'), 'secret_code', ['user_id'], unique=False)
    op.create_table('social_channels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('profile_photo_url', sa.String(length=255), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('social_category_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('allow_comments', sa.Boolean(), nullable=False),
    sa.Column('allow_reactions', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['social_category_id'], ['social_category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_social_channels_name'), 'social_channels', ['name'], unique=True)
    op.create_index(op.f('ix_social_channels_owner_id'), 'social_channels', ['owner_id'], unique=False)
    op.create_index(op.f('ix_social_channels_social_category_id'), 'social_channels', ['social_category_id'], unique=False)
    op.create_table('social_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('mimetype', sa.String(length=100), nullable=True),
    sa.Column('filepath', sa.String(length=255), nullable=False),
    sa.Column('size', sa.BigInteger(), nullable=False),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('filepath')
    )
    op.create_table('social_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('profile_photo_url', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_social_group_owner_id'), 'social_group', ['owner_id'], unique=False)
    op.create_table('staff_attendance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('present', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', name='_staff_attendance_uc')
    )
    op.create_index(op.f('ix_staff_attendance_date'), 'staff_attendance', ['date'], unique=False)
    op.create_index(op.f('ix_staff_attendance_user_id'), 'staff_attendance', ['user_id'], unique=False)
    op.create_table('student_attendance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'date', name='_student_date_uc')
    )
    op.create_index(op.f('ix_student_attendance_date'), 'student_attendance', ['date'], unique=False)
    op.create_index(op.f('ix_student_attendance_student_id'), 'student_attendance', ['student_id'], unique=False)
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('grade', sa.String(length=10), nullable=True),
    sa.Column('section', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('talent_club_bans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('issued_by_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('issued_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['issued_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_talent_club_bans_issued_by_id'), 'talent_club_bans', ['issued_by_id'], unique=False)
    op.create_index(op.f('ix_talent_club_bans_user_id'), 'talent_club_bans', ['user_id'], unique=False)
    op.create_table('talent_club_community_members',
    sa.Column('community_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['community_id'], ['talent_club_community.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('community_id', 'user_id'),
    sa.UniqueConstraint('community_id', 'user_id', name='_tcc_membership_uc')
    )
    op.create_table('talent_club_instances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('profile_photo_url', sa.String(length=255), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('social_category_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('warning_count', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['social_category_id'], ['social_category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_talent_club_instances_name'), 'talent_club_instances', ['name'], unique=True)
    op.create_index(op.f('ix_talent_club_instances_owner_id'), 'talent_club_instances', ['owner_id'], unique=False)
    op.create_index(op.f('ix_talent_club_instances_social_category_id'), 'talent_club_instances', ['social_category_id'], unique=False)
    op.create_table('talent_club_penalties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('issued_by_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('issued_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['issued_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_talent_club_penalties_issued_by_id'), 'talent_club_penalties', ['issued_by_id'], unique=False)
    op.create_index(op.f('ix_talent_club_penalties_user_id'), 'talent_club_penalties', ['user_id'], unique=False)
    op.create_table('task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('urgency', sa.String(length=20), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_task_created_at', 'task', ['created_at'], unique=False)
    op.create_index('idx_task_creator', 'task', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_task_created_by_id'), 'task', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_task_title'), 'task', ['title'], unique=False)
    op.create_table('tc_leader_elections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('initiated_by_id', sa.Integer(), nullable=False),
    sa.Column('initiated_at', sa.DateTime(), nullable=False),
    sa.Column('concluded_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('elected_leader_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['elected_leader_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['initiated_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tc_leader_elections_elected_leader_id'), 'tc_leader_elections', ['elected_leader_id'], unique=False)
    op.create_index(op.f('ix_tc_leader_elections_initiated_by_id'), 'tc_leader_elections', ['initiated_by_id'], unique=False)
    op.create_index(op.f('ix_tc_leader_elections_status'), 'tc_leader_elections', ['status'], unique=False)
    op.create_table('teacher_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=100), nullable=False),
    sa.Column('salary', sa.Float(), nullable=True),
    sa.Column('grade', sa.String(length=10), nullable=True),
    sa.Column('section', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teacher_profile_user_id'), 'teacher_profile', ['user_id'], unique=False)
    op.create_table('user_channel_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('security_type', sa.String(length=20), nullable=True),
    sa.Column('security_payload_hash', sa.String(length=255), nullable=True),
    sa.Column('_metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='_user_category_name_uc')
    )
    op.create_index('idx_user_channel_category_user_order', 'user_channel_category', ['user_id', 'order'], unique=False)
    op.create_index(op.f('ix_user_channel_category_user_id'), 'user_channel_category', ['user_id'], unique=False)
    op.create_table('user_saved_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('item_type', sa.String(length=50), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('saved_at', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('custom_tags', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'item_type', 'item_id', name='_user_saved_item_uc')
    )
    op.create_index('idx_user_item_type_id', 'user_saved_item', ['user_id', 'item_type', 'item_id'], unique=False)
    op.create_index(op.f('ix_user_saved_item_item_id'), 'user_saved_item', ['item_id'], unique=False)
    op.create_index(op.f('ix_user_saved_item_item_type'), 'user_saved_item', ['item_type'], unique=False)
    op.create_index(op.f('ix_user_saved_item_saved_at'), 'user_saved_item', ['saved_at'], unique=False)
    op.create_index(op.f('ix_user_saved_item_user_id'), 'user_saved_item', ['user_id'], unique=False)
    op.create_table('asset_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=True),
    sa.Column('reported_by_id', sa.Integer(), nullable=False),
    sa.Column('report_date', sa.DateTime(), nullable=False),
    sa.Column('damage_description', sa.Text(), nullable=False),
    sa.Column('date_of_damage', sa.Date(), nullable=True),
    sa.Column('quantity_damaged', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('resolved_by_id', sa.Integer(), nullable=True),
    sa.Column('resolved_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ),
    sa.ForeignKeyConstraint(['reported_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['resolved_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_asset_report_asset', 'asset_reports', ['asset_id'], unique=False)
    op.create_index('idx_asset_report_date', 'asset_reports', ['report_date'], unique=False)
    op.create_index('idx_asset_report_reporter', 'asset_reports', ['reported_by_id'], unique=False)
    op.create_index('idx_asset_report_resolver', 'asset_reports', ['resolved_by_id'], unique=False)
    op.create_index('idx_asset_report_status', 'asset_reports', ['status'], unique=False)
    op.create_index(op.f('ix_asset_reports_asset_id'), 'asset_reports', ['asset_id'], unique=False)
    op.create_index(op.f('ix_asset_reports_report_date'), 'asset_reports', ['report_date'], unique=False)
    op.create_index(op.f('ix_asset_reports_reported_by_id'), 'asset_reports', ['reported_by_id'], unique=False)
    op.create_index(op.f('ix_asset_reports_status'), 'asset_reports', ['status'], unique=False)
    op.create_table('book_checkout',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('checkout_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('return_date', sa.Date(), nullable=True),
    sa.Column('returned', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_book_checkout_dates', 'book_checkout', ['checkout_date', 'due_date', 'return_date'], unique=False)
    op.create_index(op.f('ix_book_checkout_asset_id'), 'book_checkout', ['asset_id'], unique=False)
    op.create_index(op.f('ix_book_checkout_returned'), 'book_checkout', ['returned'], unique=False)
    op.create_index(op.f('ix_book_checkout_user_id'), 'book_checkout', ['user_id'], unique=False)
    op.create_table('borrowed_asset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('checkout_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('return_date', sa.Date(), nullable=True),
    sa.Column('returned', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_borrowed_asset_asset_id'), 'borrowed_asset', ['asset_id'], unique=False)
    op.create_index(op.f('ix_borrowed_asset_returned'), 'borrowed_asset', ['returned'], unique=False)
    op.create_index(op.f('ix_borrowed_asset_user_id'), 'borrowed_asset', ['user_id'], unique=False)
    op.create_table('global_post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('file_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('is_edited', sa.Boolean(), nullable=False),
    sa.Column('visibility', sa.String(length=20), nullable=False),
    sa.Column('allow_comments', sa.Boolean(), nullable=False),
    sa.Column('allow_likes', sa.Boolean(), nullable=False),
    sa.Column('shared_post_id', sa.Integer(), nullable=True),
    sa.Column('_metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['file_id'], ['social_files.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['shared_post_id'], ['global_post.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_global_post_author_id'), 'global_post', ['author_id'], unique=False)
    op.create_index(op.f('ix_global_post_file_id'), 'global_post', ['file_id'], unique=True)
    op.create_index(op.f('ix_global_post_shared_post_id'), 'global_post', ['shared_post_id'], unique=False)
    op.create_index(op.f('ix_global_post_timestamp'), 'global_post', ['timestamp'], unique=False)
    op.create_index(op.f('ix_global_post_visibility'), 'global_post', ['visibility'], unique=False)
    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('receiver_id', sa.Integer(), nullable=False),
    sa.Column('sender_role', sa.String(length=50), nullable=True),
    sa.Column('receiver_role', sa.String(length=50), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('file_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['social_files.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['receiver_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_message_pair', 'message', ['sender_id', 'receiver_id'], unique=False)
    op.create_index('idx_message_status', 'message', ['is_read'], unique=False)
    op.create_index('idx_message_timestamp', 'message', ['timestamp'], unique=False)
    op.create_index(op.f('ix_message_is_read'), 'message', ['is_read'], unique=False)
    op.create_index(op.f('ix_message_receiver_id'), 'message', ['receiver_id'], unique=False)
    op.create_index(op.f('ix_message_sender_id'), 'message', ['sender_id'], unique=False)
    op.create_index(op.f('ix_message_timestamp'), 'message', ['timestamp'], unique=False)
    op.create_table('parent_student',
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('verification_status', sa.String(length=20), nullable=True),
    sa.Column('relationship', sa.String(length=50), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['parent.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('parent_id', 'student_id')
    )
    op.create_table('request_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('changed_by_id', sa.Integer(), nullable=False),
    sa.Column('old_status', sa.String(length=20), nullable=True),
    sa.Column('new_status', sa.String(length=20), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['changed_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['request.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_request_history_request_ts', 'request_history', ['request_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_request_history_changed_by_id'), 'request_history', ['changed_by_id'], unique=False)
    op.create_index(op.f('ix_request_history_request_id'), 'request_history', ['request_id'], unique=False)
    op.create_table('social_channel_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('file_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('is_edited', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['channel_id'], ['social_channels.id'], ),
    sa.ForeignKeyConstraint(['file_id'], ['social_files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_social_channel_posts_author_id'), 'social_channel_posts', ['author_id'], unique=False)
    op.create_index(op.f('ix_social_channel_posts_channel_id'), 'social_channel_posts', ['channel_id'], unique=False)
    op.create_index(op.f('ix_social_channel_posts_file_id'), 'social_channel_posts', ['file_id'], unique=True)
    op.create_index(op.f('ix_social_channel_posts_timestamp'), 'social_channel_posts', ['timestamp'], unique=False)
    op.create_table('social_channel_subscribers',
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('subscribed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['social_channels.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('channel_id', 'user_id'),
    sa.UniqueConstraint('channel_id', 'user_id', name='_channel_user_uc')
    )
    op.create_table('social_group_member',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['social_group.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('group_id', 'user_id'),
    sa.UniqueConstraint('group_id', 'user_id', name='_group_user_uc')
    )
    op.create_table('social_group_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('file_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('is_edited', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['file_id'], ['social_files.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['social_group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_social_group_messages_author_id'), 'social_group_messages', ['author_id'], unique=False)
    op.create_index(op.f('ix_social_group_messages_file_id'), 'social_group_messages', ['file_id'], unique=True)
    op.create_index(op.f('ix_social_group_messages_group_id'), 'social_group_messages', ['group_id'], unique=False)
    op.create_index(op.f('ix_social_group_messages_timestamp'), 'social_group_messages', ['timestamp'], unique=False)
    op.create_table('talent_club_community_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('community_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('file_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('is_edited', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['community_id'], ['talent_club_community.id'], ),
    sa.ForeignKeyConstraint(['file_id'], ['social_files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_talent_club_community_messages_author_id'), 'talent_club_community_messages', ['author_id'], unique=False)
    op.create_index(op.f('ix_talent_club_community_messages_community_id'), 'talent_club_community_messages', ['community_id'], unique=False)
    op.create_index(op.f('ix_talent_club_community_messages_file_id'), 'talent_club_community_messages', ['file_id'], unique=True)
    op.create_index(op.f('ix_talent_club_community_messages_timestamp'), 'talent_club_community_messages', ['timestamp'], unique=False)
    op.create_table('talent_club_feeds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('talent_club_id', sa.Integer(), nullable=False),
    sa.Column('allow_comments', sa.Boolean(), nullable=False),
    sa.Column('allow_reactions', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['talent_club_id'], ['talent_club_instances.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('talent_club_id')
    )
    op.create_table('talent_club_follows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('talent_club_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('followed_at', sa.DateTime(), nullable=False),
    sa.Column('receive_notifications', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['talent_club_id'], ['talent_club_instances.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('talent_club_id', 'user_id', name='_tc_follow_uc')
    )
    op.create_index(op.f('ix_talent_club_follows_talent_club_id'), 'talent_club_follows', ['talent_club_id'], unique=False)
    op.create_index(op.f('ix_talent_club_follows_user_id'), 'talent_club_follows', ['user_id'], unique=False)
    op.create_table('talent_club_memberships',
    sa.Column('talent_club_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['talent_club_id'], ['talent_club_instances.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('talent_club_id', 'user_id'),
    sa.UniqueConstraint('talent_club_id', 'user_id', name='_tc_membership_uc')
    )
    op.create_table('talent_club_proposals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('social_category_id', sa.Integer(), nullable=False),
    sa.Column('proposal_file_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('leader_review_notes', sa.Text(), nullable=True),
    sa.Column('reviewed_by_id', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['proposal_file_id'], ['social_files.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['social_category_id'], ['social_category.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('proposal_file_id')
    )
    op.create_index(op.f('ix_talent_club_proposals_creator_id'), 'talent_club_proposals', ['creator_id'], unique=False)
    op.create_index(op.f('ix_talent_club_proposals_reviewed_by_id'), 'talent_club_proposals', ['reviewed_by_id'], unique=False)
    op.create_index(op.f('ix_talent_club_proposals_social_category_id'), 'talent_club_proposals', ['social_category_id'], unique=False)
    op.create_index(op.f('ix_talent_club_proposals_status'), 'talent_club_proposals', ['status'], unique=False)
    op.create_table('talent_club_warnings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('talent_club_id', sa.Integer(), nullable=False),
    sa.Column('issued_by_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('issued_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['issued_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['talent_club_id'], ['talent_club_instances.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_talent_club_warnings_issued_by_id'), 'talent_club_warnings', ['issued_by_id'], unique=False)
    op.create_index(op.f('ix_talent_club_warnings_talent_club_id'), 'talent_club_warnings', ['talent_club_id'], unique=False)
    op.create_table('tc_leader_votes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('election_id', sa.Integer(), nullable=False),
    sa.Column('voter_id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('voted_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['election_id'], ['tc_leader_elections.id'], ),
    sa.ForeignKeyConstraint(['voter_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('election_id', 'voter_id', name='_tc_leader_vote_uc')
    )
    op.create_index(op.f('ix_tc_leader_votes_candidate_id'), 'tc_leader_votes', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_tc_leader_votes_election_id'), 'tc_leader_votes', ['election_id'], unique=False)
    op.create_index(op.f('ix_tc_leader_votes_voter_id'), 'tc_leader_votes', ['voter_id'], unique=False)
    op.create_table('user_channel_preference',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('is_pinned', sa.Boolean(), nullable=False),
    sa.Column('pinned_order', sa.Integer(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('is_hidden', sa.Boolean(), nullable=False),
    sa.Column('last_accessed_at', sa.DateTime(), nullable=True),
    sa.Column('user_category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['social_channels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_category_id'], ['user_channel_category.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'channel_id')
    )
    op.create_index('idx_user_channel_pref_user_pinned', 'user_channel_preference', ['user_id', 'is_pinned'], unique=False)
    op.create_index(op.f('ix_user_channel_preference_is_archived'), 'user_channel_preference', ['is_archived'], unique=False)
    op.create_index(op.f('ix_user_channel_preference_is_pinned'), 'user_channel_preference', ['is_pinned'], unique=False)
    op.create_index(op.f('ix_user_channel_preference_user_category_id'), 'user_channel_preference', ['user_category_id'], unique=False)
    op.create_table('user_task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=False),
    sa.Column('assigned_by_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('completion_notes', sa.Text(), nullable=True),
    sa.Column('last_status_update_at', sa.DateTime(), nullable=False),
    sa.Column('reviewed_by_id', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('reviewer_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id', 'user_id', name='_task_user_uc')
    )
    op.create_index('idx_user_task_reviewed_by', 'user_task', ['reviewed_by_id'], unique=False)
    op.create_index('idx_user_task_task_status', 'user_task', ['task_id', 'status'], unique=False)
    op.create_index('idx_user_task_user_status', 'user_task', ['user_id', 'status'], unique=False)
    op.create_index(op.f('ix_user_task_status'), 'user_task', ['status'], unique=False)
    op.create_index(op.f('ix_user_task_task_id'), 'user_task', ['task_id'], unique=False)
    op.create_index(op.f('ix_user_task_user_id'), 'user_task', ['user_id'], unique=False)
    op.create_table('global_comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('parent_comment_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('is_edited', sa.Boolean(), nullable=False),
    sa.Column('_metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_comment_id'], ['global_comment.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['global_post.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_global_comment_author_id'), 'global_comment', ['author_id'], unique=False)
    op.create_index(op.f('ix_global_comment_parent_comment_id'), 'global_comment', ['parent_comment_id'], unique=False)
    op.create_index(op.f('ix_global_comment_post_id'), 'global_comment', ['post_id'], unique=False)
    op.create_index(op.f('ix_global_comment_timestamp'), 'global_comment', ['timestamp'], unique=False)
    op.create_table('global_like',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['global_post.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id', 'user_id', name='_global_post_user_like_uc')
    )
    op.create_index('idx_global_like_post_user', 'global_like', ['post_id', 'user_id'], unique=False)
    op.create_table('social_channel_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['social_channel_posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_social_channel_comments_timestamp'), 'social_channel_comments', ['timestamp'], unique=False)
    op.create_table('social_channel_reactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('emoji', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['social_channel_posts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id', 'user_id', 'emoji', name='_post_user_emoji_uc')
    )
    op.create_table('talent_club_feed_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('feed_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('file_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('is_edited', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['feed_id'], ['talent_club_feeds.id'], ),
    sa.ForeignKeyConstraint(['file_id'], ['social_files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_talent_club_feed_posts_author_id'), 'talent_club_feed_posts', ['author_id'], unique=False)
    op.create_index(op.f('ix_talent_club_feed_posts_feed_id'), 'talent_club_feed_posts', ['feed_id'], unique=False)
    op.create_index(op.f('ix_talent_club_feed_posts_file_id'), 'talent_club_feed_posts', ['file_id'], unique=True)
    op.create_index(op.f('ix_talent_club_feed_posts_timestamp'), 'talent_club_feed_posts', ['timestamp'], unique=False)
    op.create_table('talent_club_proposal_mentions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proposal_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('responded_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['proposal_id'], ['talent_club_proposals.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('proposal_id', 'user_id', name='_tc_proposal_mention_uc')
    )
    op.create_index(op.f('ix_talent_club_proposal_mentions_proposal_id'), 'talent_club_proposal_mentions', ['proposal_id'], unique=False)
    op.create_index(op.f('ix_talent_club_proposal_mentions_status'), 'talent_club_proposal_mentions', ['status'], unique=False)
    op.create_index(op.f('ix_talent_club_proposal_mentions_user_id'), 'talent_club_proposal_mentions', ['user_id'], unique=False)
    op.create_table('task_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_task_id', sa.Integer(), nullable=False),
    sa.Column('changed_by_id', sa.Integer(), nullable=False),
    sa.Column('old_status', sa.String(length=30), nullable=True),
    sa.Column('new_status', sa.String(length=30), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['changed_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_task_id'], ['user_task.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_task_history_usertask_ts', 'task_history', ['user_task_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_task_history_timestamp'), 'task_history', ['timestamp'], unique=False)
    op.create_index(op.f('ix_task_history_user_task_id'), 'task_history', ['user_task_id'], unique=False)
    op.create_table('talent_club_feed_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['talent_club_feed_posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_talent_club_feed_comments_post_id'), 'talent_club_feed_comments', ['post_id'], unique=False)
    op.create_index(op.f('ix_talent_club_feed_comments_timestamp'), 'talent_club_feed_comments', ['timestamp'], unique=False)
    op.create_table('talent_club_feed_reactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('emoji', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['talent_club_feed_posts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id', 'user_id', 'emoji', name='_tc_post_user_emoji_uc')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('talent_club_feed_reactions')
    op.drop_index(op.f('ix_talent_club_feed_comments_timestamp'), table_name='talent_club_feed_comments')
    op.drop_index(op.f('ix_talent_club_feed_comments_post_id'), table_name='talent_club_feed_comments')
    op.drop_table('talent_club_feed_comments')
    op.drop_index(op.f('ix_task_history_user_task_id'), table_name='task_history')
    op.drop_index(op.f('ix_task_history_timestamp'), table_name='task_history')
    op.drop_index('idx_task_history_usertask_ts', table_name='task_history')
    op.drop_table('task_history')
    op.drop_index(op.f('ix_talent_club_proposal_mentions_user_id'), table_name='talent_club_proposal_mentions')
    op.drop_index(op.f('ix_talent_club_proposal_mentions_status'), table_name='talent_club_proposal_mentions')
    op.drop_index(op.f('ix_talent_club_proposal_mentions_proposal_id'), table_name='talent_club_proposal_mentions')
    op.drop_table('talent_club_proposal_mentions')
    op.drop_index(op.f('ix_talent_club_feed_posts_timestamp'), table_name='talent_club_feed_posts')
    op.drop_index(op.f('ix_talent_club_feed_posts_file_id'), table_name='talent_club_feed_posts')
    op.drop_index(op.f('ix_talent_club_feed_posts_feed_id'), table_name='talent_club_feed_posts')
    op.drop_index(op.f('ix_talent_club_feed_posts_author_id'), table_name='talent_club_feed_posts')
    op.drop_table('talent_club_feed_posts')
    op.drop_table('social_channel_reactions')
    op.drop_index(op.f('ix_social_channel_comments_timestamp'), table_name='social_channel_comments')
    op.drop_table('social_channel_comments')
    op.drop_index('idx_global_like_post_user', table_name='global_like')
    op.drop_table('global_like')
    op.drop_index(op.f('ix_global_comment_timestamp'), table_name='global_comment')
    op.drop_index(op.f('ix_global_comment_post_id'), table_name='global_comment')
    op.drop_index(op.f('ix_global_comment_parent_comment_id'), table_name='global_comment')
    op.drop_index(op.f('ix_global_comment_author_id'), table_name='global_comment')
    op.drop_table('global_comment')
    op.drop_index(op.f('ix_user_task_user_id'), table_name='user_task')
    op.drop_index(op.f('ix_user_task_task_id'), table_name='user_task')
    op.drop_index(op.f('ix_user_task_status'), table_name='user_task')
    op.drop_index('idx_user_task_user_status', table_name='user_task')
    op.drop_index('idx_user_task_task_status', table_name='user_task')
    op.drop_index('idx_user_task_reviewed_by', table_name='user_task')
    op.drop_table('user_task')
    op.drop_index(op.f('ix_user_channel_preference_user_category_id'), table_name='user_channel_preference')
    op.drop_index(op.f('ix_user_channel_preference_is_pinned'), table_name='user_channel_preference')
    op.drop_index(op.f('ix_user_channel_preference_is_archived'), table_name='user_channel_preference')
    op.drop_index('idx_user_channel_pref_user_pinned', table_name='user_channel_preference')
    op.drop_table('user_channel_preference')
    op.drop_index(op.f('ix_tc_leader_votes_voter_id'), table_name='tc_leader_votes')
    op.drop_index(op.f('ix_tc_leader_votes_election_id'), table_name='tc_leader_votes')
    op.drop_index(op.f('ix_tc_leader_votes_candidate_id'), table_name='tc_leader_votes')
    op.drop_table('tc_leader_votes')
    op.drop_index(op.f('ix_talent_club_warnings_talent_club_id'), table_name='talent_club_warnings')
    op.drop_index(op.f('ix_talent_club_warnings_issued_by_id'), table_name='talent_club_warnings')
    op.drop_table('talent_club_warnings')
    op.drop_index(op.f('ix_talent_club_proposals_status'), table_name='talent_club_proposals')
    op.drop_index(op.f('ix_talent_club_proposals_social_category_id'), table_name='talent_club_proposals')
    op.drop_index(op.f('ix_talent_club_proposals_reviewed_by_id'), table_name='talent_club_proposals')
    op.drop_index(op.f('ix_talent_club_proposals_creator_id'), table_name='talent_club_proposals')
    op.drop_table('talent_club_proposals')
    op.drop_table('talent_club_memberships')
    op.drop_index(op.f('ix_talent_club_follows_user_id'), table_name='talent_club_follows')
    op.drop_index(op.f('ix_talent_club_follows_talent_club_id'), table_name='talent_club_follows')
    op.drop_table('talent_club_follows')
    op.drop_table('talent_club_feeds')
    op.drop_index(op.f('ix_talent_club_community_messages_timestamp'), table_name='talent_club_community_messages')
    op.drop_index(op.f('ix_talent_club_community_messages_file_id'), table_name='talent_club_community_messages')
    op.drop_index(op.f('ix_talent_club_community_messages_community_id'), table_name='talent_club_community_messages')
    op.drop_index(op.f('ix_talent_club_community_messages_author_id'), table_name='talent_club_community_messages')
    op.drop_table('talent_club_community_messages')
    op.drop_index(op.f('ix_social_group_messages_timestamp'), table_name='social_group_messages')
    op.drop_index(op.f('ix_social_group_messages_group_id'), table_name='social_group_messages')
    op.drop_index(op.f('ix_social_group_messages_file_id'), table_name='social_group_messages')
    op.drop_index(op.f('ix_social_group_messages_author_id'), table_name='social_group_messages')
    op.drop_table('social_group_messages')
    op.drop_table('social_group_member')
    op.drop_table('social_channel_subscribers')
    op.drop_index(op.f('ix_social_channel_posts_timestamp'), table_name='social_channel_posts')
    op.drop_index(op.f('ix_social_channel_posts_file_id'), table_name='social_channel_posts')
    op.drop_index(op.f('ix_social_channel_posts_channel_id'), table_name='social_channel_posts')
    op.drop_index(op.f('ix_social_channel_posts_author_id'), table_name='social_channel_posts')
    op.drop_table('social_channel_posts')
    op.drop_index(op.f('ix_request_history_request_id'), table_name='request_history')
    op.drop_index(op.f('ix_request_history_changed_by_id'), table_name='request_history')
    op.drop_index('idx_request_history_request_ts', table_name='request_history')
    op.drop_table('request_history')
    op.drop_table('parent_student')
    op.drop_index(op.f('ix_message_timestamp'), table_name='message')
    op.drop_index(op.f('ix_message_sender_id'), table_name='message')
    op.drop_index(op.f('ix_message_receiver_id'), table_name='message')
    op.drop_index(op.f('ix_message_is_read'), table_name='message')
    op.drop_index('idx_message_timestamp', table_name='message')
    op.drop_index('idx_message_status', table_name='message')
    op.drop_index('idx_message_pair', table_name='message')
    op.drop_table('message')
    op.drop_index(op.f('ix_global_post_visibility'), table_name='global_post')
    op.drop_index(op.f('ix_global_post_timestamp'), table_name='global_post')
    op.drop_index(op.f('ix_global_post_shared_post_id'), table_name='global_post')
    op.drop_index(op.f('ix_global_post_file_id'), table_name='global_post')
    op.drop_index(op.f('ix_global_post_author_id'), table_name='global_post')
    op.drop_table('global_post')
    op.drop_index(op.f('ix_borrowed_asset_user_id'), table_name='borrowed_asset')
    op.drop_index(op.f('ix_borrowed_asset_returned'), table_name='borrowed_asset')
    op.drop_index(op.f('ix_borrowed_asset_asset_id'), table_name='borrowed_asset')
    op.drop_table('borrowed_asset')
    op.drop_index(op.f('ix_book_checkout_user_id'), table_name='book_checkout')
    op.drop_index(op.f('ix_book_checkout_returned'), table_name='book_checkout')
    op.drop_index(op.f('ix_book_checkout_asset_id'), table_name='book_checkout')
    op.drop_index('idx_book_checkout_dates', table_name='book_checkout')
    op.drop_table('book_checkout')
    op.drop_index(op.f('ix_asset_reports_status'), table_name='asset_reports')
    op.drop_index(op.f('ix_asset_reports_reported_by_id'), table_name='asset_reports')
    op.drop_index(op.f('ix_asset_reports_report_date'), table_name='asset_reports')
    op.drop_index(op.f('ix_asset_reports_asset_id'), table_name='asset_reports')
    op.drop_index('idx_asset_report_status', table_name='asset_reports')
    op.drop_index('idx_asset_report_resolver', table_name='asset_reports')
    op.drop_index('idx_asset_report_reporter', table_name='asset_reports')
    op.drop_index('idx_asset_report_date', table_name='asset_reports')
    op.drop_index('idx_asset_report_asset', table_name='asset_reports')
    op.drop_table('asset_reports')
    op.drop_index(op.f('ix_user_saved_item_user_id'), table_name='user_saved_item')
    op.drop_index(op.f('ix_user_saved_item_saved_at'), table_name='user_saved_item')
    op.drop_index(op.f('ix_user_saved_item_item_type'), table_name='user_saved_item')
    op.drop_index(op.f('ix_user_saved_item_item_id'), table_name='user_saved_item')
    op.drop_index('idx_user_item_type_id', table_name='user_saved_item')
    op.drop_table('user_saved_item')
    op.drop_index(op.f('ix_user_channel_category_user_id'), table_name='user_channel_category')
    op.drop_index('idx_user_channel_category_user_order', table_name='user_channel_category')
    op.drop_table('user_channel_category')
    op.drop_index(op.f('ix_teacher_profile_user_id'), table_name='teacher_profile')
    op.drop_table('teacher_profile')
    op.drop_index(op.f('ix_tc_leader_elections_status'), table_name='tc_leader_elections')
    op.drop_index(op.f('ix_tc_leader_elections_initiated_by_id'), table_name='tc_leader_elections')
    op.drop_index(op.f('ix_tc_leader_elections_elected_leader_id'), table_name='tc_leader_elections')
    op.drop_table('tc_leader_elections')
    op.drop_index(op.f('ix_task_title'), table_name='task')
    op.drop_index(op.f('ix_task_created_by_id'), table_name='task')
    op.drop_index('idx_task_creator', table_name='task')
    op.drop_index('idx_task_created_at', table_name='task')
    op.drop_table('task')
    op.drop_index(op.f('ix_talent_club_penalties_user_id'), table_name='talent_club_penalties')
    op.drop_index(op.f('ix_talent_club_penalties_issued_by_id'), table_name='talent_club_penalties')
    op.drop_table('talent_club_penalties')
    op.drop_index(op.f('ix_talent_club_instances_social_category_id'), table_name='talent_club_instances')
    op.drop_index(op.f('ix_talent_club_instances_owner_id'), table_name='talent_club_instances')
    op.drop_index(op.f('ix_talent_club_instances_name'), table_name='talent_club_instances')
    op.drop_table('talent_club_instances')
    op.drop_table('talent_club_community_members')
    op.drop_index(op.f('ix_talent_club_bans_user_id'), table_name='talent_club_bans')
    op.drop_index(op.f('ix_talent_club_bans_issued_by_id'), table_name='talent_club_bans')
    op.drop_table('talent_club_bans')
    op.drop_table('students')
    op.drop_index(op.f('ix_student_attendance_student_id'), table_name='student_attendance')
    op.drop_index(op.f('ix_student_attendance_date'), table_name='student_attendance')
    op.drop_table('student_attendance')
    op.drop_index(op.f('ix_staff_attendance_user_id'), table_name='staff_attendance')
    op.drop_index(op.f('ix_staff_attendance_date'), table_name='staff_attendance')
    op.drop_table('staff_attendance')
    op.drop_index(op.f('ix_social_group_owner_id'), table_name='social_group')
    op.drop_table('social_group')
    op.drop_table('social_files')
    op.drop_index(op.f('ix_social_channels_social_category_id'), table_name='social_channels')
    op.drop_index(op.f('ix_social_channels_owner_id'), table_name='social_channels')
    op.drop_index(op.f('ix_social_channels_name'), table_name='social_channels')
    op.drop_table('social_channels')
    op.drop_index(op.f('ix_secret_code_user_id'), table_name='secret_code')
    op.drop_index(op.f('ix_secret_code_code'), table_name='secret_code')
    op.drop_table('secret_code')
    op.drop_index(op.f('ix_request_title'), table_name='request')
    op.drop_index(op.f('ix_request_tier'), table_name='request')
    op.drop_index(op.f('ix_request_status'), table_name='request')
    op.drop_index(op.f('ix_request_requester_id'), table_name='request')
    op.drop_index(op.f('ix_request_last_forwarded_by_id'), table_name='request')
    op.drop_index(op.f('ix_request_current_handler_id'), table_name='request')
    op.drop_index('idx_request_status_tier', table_name='request')
    op.drop_index('idx_request_requester_status', table_name='request')
    op.drop_table('request')
    op.drop_table('parent')
    op.drop_index(op.f('ix_notification_timestamp'), table_name='notification')
    op.drop_index(op.f('ix_notification_sender_id'), table_name='notification')
    op.drop_index(op.f('ix_notification_related_object_id'), table_name='notification')
    op.drop_index(op.f('ix_notification_receiver_id'), table_name='notification')
    op.drop_index(op.f('ix_notification_is_read'), table_name='notification')
    op.drop_index('idx_notification_receiver_read', table_name='notification')
    op.drop_table('notification')
    op.drop_index(op.f('ix_mark_subject'), table_name='mark')
    op.drop_index(op.f('ix_mark_student_id'), table_name='mark')
    op.drop_index(op.f('ix_mark_average'), table_name='mark')
    op.drop_index('idx_mark_subject_average', table_name='mark')
    op.drop_table('mark')
    op.drop_table('library_log')
    op.drop_index(op.f('ix_behavior_record_student_id'), table_name='behavior_record')
    op.drop_index(op.f('ix_behavior_record_recorded_by_id'), table_name='behavior_record')
    op.drop_index(op.f('ix_behavior_record_is_resolved'), table_name='behavior_record')
    op.drop_index(op.f('ix_behavior_record_date'), table_name='behavior_record')
    op.drop_index('idx_behavior_student_date', table_name='behavior_record')
    op.drop_table('behavior_record')
    op.drop_index(op.f('ix_asset_status'), table_name='asset')
    op.drop_index(op.f('ix_asset_name'), table_name='asset')
    op.drop_index(op.f('ix_asset_lab_id'), table_name='asset')
    op.drop_index(op.f('ix_asset_category_id'), table_name='asset')
    op.drop_index(op.f('ix_asset_added_by_user_id'), table_name='asset')
    op.drop_table('asset')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_section'), table_name='user')
    op.drop_index(op.f('ix_user_leader_id'), table_name='user')
    op.drop_index(op.f('ix_user_grade'), table_name='user')
    op.drop_index(op.f('ix_user_full_name'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('talent_club_community')
    op.drop_table('social_category')
    op.drop_table('role')
    op.drop_table('lab')
    op.drop_table('asset_category')
    # ### end Alembic commands ###
