"""add comment post and url

Revision ID: 773eade80ffc
Revises: 8ffbbfcf5a23
Create Date: 2025-06-07 15:08:23.728935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '773eade80ffc'
down_revision = '8ffbbfcf5a23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('global_post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('file_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('is_edited', sa.Boolean(), nullable=False),
    sa.Column('visibility', sa.String(length=20), nullable=False),
    sa.Column('allow_comments', sa.Boolean(), nullable=False),
    sa.Column('allow_likes', sa.Boolean(), nullable=False),
    sa.Column('shared_post_id', sa.Integer(), nullable=True),
    sa.Column('_metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['file_id'], ['social_files.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['shared_post_id'], ['global_post.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_global_post_author_id'), 'global_post', ['author_id'], unique=False)
    op.create_index(op.f('ix_global_post_file_id'), 'global_post', ['file_id'], unique=True)
    op.create_index(op.f('ix_global_post_shared_post_id'), 'global_post', ['shared_post_id'], unique=False)
    op.create_index(op.f('ix_global_post_timestamp'), 'global_post', ['timestamp'], unique=False)
    op.create_index(op.f('ix_global_post_visibility'), 'global_post', ['visibility'], unique=False)
    op.create_table('global_comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('parent_comment_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('is_edited', sa.Boolean(), nullable=False),
    sa.Column('_metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_comment_id'], ['global_comment.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['global_post.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_global_comment_author_id'), 'global_comment', ['author_id'], unique=False)
    op.create_index(op.f('ix_global_comment_parent_comment_id'), 'global_comment', ['parent_comment_id'], unique=False)
    op.create_index(op.f('ix_global_comment_post_id'), 'global_comment', ['post_id'], unique=False)
    op.create_index(op.f('ix_global_comment_timestamp'), 'global_comment', ['timestamp'], unique=False)
    op.create_table('global_like',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['global_post.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id', 'user_id', name='_global_post_user_like_uc')
    )
    op.create_index('idx_global_like_post_user', 'global_like', ['post_id', 'user_id'], unique=False)

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_global_like_post_user', table_name='global_like')
    op.drop_table('global_like')
    op.drop_index(op.f('ix_global_comment_timestamp'), table_name='global_comment')
    op.drop_index(op.f('ix_global_comment_post_id'), table_name='global_comment')
    op.drop_index(op.f('ix_global_comment_parent_comment_id'), table_name='global_comment')
    op.drop_index(op.f('ix_global_comment_author_id'), table_name='global_comment')
    op.drop_table('global_comment')
    op.drop_index(op.f('ix_global_post_visibility'), table_name='global_post')
    op.drop_index(op.f('ix_global_post_timestamp'), table_name='global_post')
    op.drop_index(op.f('ix_global_post_shared_post_id'), table_name='global_post')
    op.drop_index(op.f('ix_global_post_file_id'), table_name='global_post')
    op.drop_index(op.f('ix_global_post_author_id'), table_name='global_post')
    op.drop_table('global_post')
    # ### end Alembic commands ###
