"""Add created_at column to Asset table

Revision ID: 8ffbbfcf5a23
Revises: 23d3f6483114
Create Date: 2025-06-05 12:46:55.178721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ffbbfcf5a23'
down_revision = '23d3f6483114'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asset', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    
 #   op.create_unique_constraint('_channel_user_uc', 'social_channel_subscribers', ['channel_id', 'user_id'])
  #  op.create_unique_constraint('_group_user_uc', 'social_group_members', ['group_id', 'user_id'])
    #op.create_unique_constraint('_tcc_membership_uc', 'talent_club_community_members', ['community_id', 'user_id'])
    #op.create_unique_constraint('_tc_membership_uc', 'talent_club_memberships', ['talent_club_id', 'user_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_constraint('_tc_membership_uc', 'talent_club_memberships', type_='unique')
    #op.drop_constraint('_tcc_membership_uc', 'talent_club_community_members', type_='unique')
   # op.drop_constraint('_group_user_uc', 'social_group_members', type_='unique')
   # op.drop_constraint('_channel_user_uc', 'social_channel_subscribers', type_='unique')
    op.drop_column('asset', 'created_at')
    # ### end Alembic commands ###
