"""Add ChannelSubscriber model

Revision ID: cef78c397094
Revises: b289ba58be20
Create Date: 2025-06-19 13:30:55.773879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cef78c397094'
down_revision = 'b289ba58be20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('social_channel_subscribers',
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('subscribed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['social_channels.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('channel_id', 'user_id'),
    sa.UniqueConstraint('channel_id', 'user_id', name='_channel_user_uc')
    )
    

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.drop_table('social_channel_subscribers')
    # ### end Alembic commands ###
