"""library

Revision ID: cf89de628ff8
Revises: d14b1c2cd201
Create Date: 2025-06-18 15:16:20.085721

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cf89de628ff8'
down_revision = 'd14b1c2cd201'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.add_column('library_log', sa.Column('date', sa.Date(), nullable=False))
    op.alter_column('library_log', 'check_in_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    
    op.create_index(op.f('ix_library_log_date'), 'library_log', ['date'], unique=False)
    op.create_index(op.f('ix_library_log_user_id'), 'library_log', ['user_id'], unique=False)
    
def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.drop_index(op.f('ix_library_log_user_id'), table_name='library_log')
    op.drop_index(op.f('ix_library_log_date'), table_name='library_log')
    op.alter_column('library_log', 'check_in_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('library_log', 'date')